# Generated by Django 3.2 on 2021-04-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField(max_length=5)),
                ('nameid', models.TextField(max_length=30)),
                ('name', models.TextField(max_length=30)),
                ('rank', models.TextField(max_length=5)),
            ],
        ),
    ]
