# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - udays-tj-backend-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://personalcrdeveloper.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c78720a879f44ade999d27d172b14795 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c8c76d1e166b46c5954099a3649431ec }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_c78720a879f44ade999d27d172b14795 }}/udays-tj-backend-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'udays-tj-backend-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2c489ec4fd104d57b61c802b75600752 }}
        images: 'personalcrdeveloper.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c78720a879f44ade999d27d172b14795 }}/udays-tj-backend-app:${{ github.sha }}'